name: Android Build

on:
  workflow_dispatch:
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: '3.16.5'
         channel: 'stable'
      - run: flutter --version
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk
      - name: collect apk artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lokal-chat-apk
          path: build/app/outputs/apk/release/*.apk
